### ISSUE TITLE
Views.py items

### ISSUE THREAD

**Issue by shereengh** [BLoushi52/django_3idda#16]
@staff_member_required(login_url='login')
def create_item(request):
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
        return redirect("items-list")

    context = {"form": form}
    return render(request, "item_create.html", context)

@staff_member_required(login_url='login')
def create_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
        return redirect("items-list")

    context = {"form": form}
    return render(request, "category_create.html", context)

It's not a profile that you're creating, it's an item and category, so the variable name must be clear

**Comment by MBujaber** [comment]
Done 


@staff_member_required(login_url='login')
def create_item(request):
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            item.save()
        return redirect("items-list")

    context = {"form": form}
    return render(request, "item_create.html", context)


@staff_member_required(login_url='login')
def create_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
        return redirect("items-list")

    context = {"form": form}
    return render(request, "category_create.html", context)
